version: "3.1"

services:
  barista-db:
    container_name: barista-dev-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: DEV_PASS
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5390:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
